#dist: trusty
language: c

# /home/travis/build/dzavalishin/phantomuserland
env:
  - PHANTOM_HOME="/home/travis/build/dzavalishin/phantomuserland"
#  - PHANTOM_HOME=`pwd`


#python:
#  - "3.6"

compiler:
  - gcc
  - clang

#cache:
#  directories:
#    - $HOME/.m2

#env:
#  - LUA_PATH="/usr/local/lua/;;"

#before_install:
#  - sudo apt-get install -y lua5.1 # no socket
#  - sudo apt-get -y install luarocks


script:
  - echo PHANTOM_HOME=$PHANTOM_HOME
  - make
  - make test
